StorageFileLogs
| where OperationName has_any (
    'AbortCopyFile',
    'Cancel',
    'ChangeNotify',
    'Close',
    'Echo',
    'Ioctl',
    'Lock',
    'Logoff',
    'Negotiate',
    'OplockBreak',
    'SessionSetup',
    'TreeConnect',
    'TreeDisconnect',
    'CloseHandles',
    'AcquireFileLease',
    'BreakFileLease',
    'ChangeFileLease',
    'ReleaseFileLease' )
| summarize count() by OperationName
| order by count_ desc