StorageFileLogs
| where OperationName has_any (
    'GetFileServiceProperties',
    'GetShareACL',
    'GetShareMetadata',
    'GetShareProperties',
    'GetShareStats',
    'FilePreflightRequest',
    'GetDirectoryMetadata',
    'GetDirectoryProperties',
    'GetFile',
    'GetFileCopyInformation',
    'GetFileMetadata',
    'GetFileServiceProperties',
    'QueryDirectory',
    'QueryInfo',
    'Read',
    'GetFilePermission' )
| summarize count() by OperationName
| order by count_ desc