StorageFileLogs
| where OperationName has_any (
    'CreateShare',
    'SetFileServiceProperties', 
    'SetShareMetadata', 
    'SetShareProperties',
    'SetShareACL',
    'CopyFile',
    'Create',
    'CreateDirectory',
    'CreateFile',
    'PutRange',
    'PutRangeFromURL',
    'SetDirectoryMetadata',
    'SetFileMetadata',
    'SetFileProperties',
    'SetInfo',
    'Write',
    'PutFilePermission' )
| summarize count() by OperationName
| order by count_ desc